export ENABLE_CONTRIB=1
export CMAKE_ARGS=' /
    -DWITH_OPENGL=ON /
    -DWITH_TBB=ON /
    -DOpenGL_GL_PREFERENCE="GLVND" /
    -DWITH_NVCUVID=ON /
    -DWITH_CUDA=ON /
    -DCUDA_FAST_MATH=ON /
    -DCUDA_HOST_COMPILER="/opt/cuda/bin/gcc" /
    -DOPENCV_DNN_CUDA=OFF /
    -DBUILD_USE_SYMLINKS=ON /
    -DWITH_CLP=ON /
    -DMKL_WITH_OPENMP=OFF /
    -DLAPACK_LIBRARIES="/usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/libcblas.so" /
    -DOpenBLAS_LIB="/usr/lib/libopenblas.so" /
    -DLAPACK_CBLAS_H="/usr/include/cblas.h" /
    -DLAPACK_LAPACKE_H="/usr/include/lapacke.h" /
    -DOPENCV_GENERATE_PKGCONFIG=ON /
    -DWITH_OPENCLAMDBLAS=ON /
    -DCLAMDBLAS_ROOT_DIR="/usr/lib/cmake/clBLAS" /
    -DCLAMDBLAS_INCLUDE_DIR="/usr/include" /
    -DCLAMDFFT_ROOT_DIR="/usr/lib/cmake/clFFT" /
    -DCLAMDFFT_INCLUDE_DIR="/usr/include" /
    -DWITH_OPENCL_SVM=ON /
    -DWITH_OPENMP=ON /
    -DWITH_NGRAPH=OFF /
    -DOPENCV_ENABLE_NONFREE=ON /
    -DCUDA_ARCH_BIN="7.5" /
    -DBUILD_opencv_cnn_3dobj=OFF /
    -DWITH_GDAL=ON /
    -DWITH_VULKAN=ON /
    -DWITH_QT=ON /
    -DWITH_GTK=OFF /
    -DBUILD_JAVA=OFF /
    -DBUILD_opencv_java_bindings_gen=OFF /
    -DBUILD_opencv_rgbd=OFF /
    '


# cmake /home/seth/packages/opencv-python/opencv -G Ninja
#     -DCMAKE_INSTALL_PREFIX:PATH=/home/seth/packages/opencv-python/_skbuild/linux-x86_64-3.8/cmake-install
#     -DPYTHON_EXECUTABLE:FILEPATH=/home/seth/.virtualenvs/airsim/bin/python3.8
#     -DPYTHON_VERSION_STRING:STRING=3.8.9
#     -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8
#     -DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython3.8.so
#     -DSKBUILD:BOOL=TRUE
#     -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-l9atfhz6/overlay/lib/python3.8/site-packages/skbuild/resources/cmake
#     -DPYTHON3_EXECUTABLE=/home/seth/.virtualenvs/airsim/bin/python3.8
#     -DPYTHON3_INCLUDE_DIR=/usr/include/python3.8
#     -DPYTHON3_LIBRARY=/usr/lib/libpython3.8.so
#     -DBUILD_opencv_python3=ON
#     -DBUILD_opencv_python2=OFF
#     -DBUILD_opencv_java=OFF
#     -DOPENCV_SKIP_PYTHON_LOADER=ON
#     -DOPENCV_PYTHON3_INSTALL_PATH=python
#     -DINSTALL_CREATE_DISTRIB=ON
#     -DBUILD_opencv_apps=OFF
#     -DBUILD_opencv_freetype=OFF
#     -DBUILD_SHARED_LIBS=OFF
#     -DBUILD_TESTS=OFF
#     -DBUILD_PERF_TESTS=OFF
#     -DBUILD_DOCS=OFF


# # these are same as above
#     -DOPENCV_EXTRA_MODULES_PATH=/home/seth/packages/opencv-python/opencv_contrib/modules /
#     -DWITH_OPENGL=ON /
#     -DWITH_TBB=ON /
#     -DOpenGL_GL_PREFERENCE=GLVND /
#     -DCMAKE_INSTALL_PREFIX=/usr /
#     -DWITH_NVCUVID=ON /
#     -DWITH_CUDA=ON /
#     -DCUDA_FAST_MATH=ON /
#     -DCUDA_HOST_COMPILER=/opt/cuda/bin/gcc /
#     -DBUILD_USE_SYMLINKS=ON /
#     -DWITH_CLP=ON /
#     '-DLAPACK_LIBRARIES=/usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/libcblas.so' /
#     -DOpenBLAS_LIB=/usr/lib/libopenblas.so /
#     -DLAPACK_CBLAS_H=/usr/include/cblas.h /
#     -DLAPACK_LAPACKE_H=/usr/include/lapacke.h /
#     -DOPENCV_GENERATE_PKGCONFIG=ON /
#     -DWITH_OPENCLAMDBLAS=ON /
#     -DCLAMDBLAS_ROOT_DIR=/usr/lib/cmake/clBLAS /
#     -DCLAMDBLAS_INCLUDE_DIR=/usr/include /
#     -DCLAMDFFT_ROOT_DIR=/usr/lib/cmake/clFFT /
#     -DCLAMDFFT_INCLUDE_DIR=/usr/include /
#     -DWITH_OPENCL_SVM=ON /
#     -DMKL_WITH_OPENMP=ON /
#     -DWITH_OPENMP=ON /
#     -DWITH_NGRAPH=OFF /
#     -DOPENCV_ENABLE_NONFREE=ON /
#     '-DCUDA_ARCH_BIN=6.0 6.1 6.2 7.0 7.5' /
#     -DBUILD_opencv_cnn_3dobj=OFF /
#     -DWITH_GDAL=ON /
#     -DWITH_VULKAN=ON /
#     -DWITH_QT=ON /
#     -DWITH_GTK=OFF /
#     -DBUILD_JAVA=OFF /
#     -DBUILD_opencv_java_bindings_gen=OFF /
#     -DBUILD_opencv_rgbd=OFF /
#     -DCMAKE_BUILD_TYPE:STRING=Release
