yay -S \
#ros-noetic-actionlib \
#ros-noetic-actionlib-msgs \
ros-noetic-actionlib-tutorials \
#ros-noetic-angles \
#ros-noetic-bond \
#ros-noetic-bond-core \
#ros-noetic-bondcpp \
#ros-noetic-bondpy \
ros-noetic-catkin \
#ros-noetic-class-loader \
#ros-noetic-cmake-modules \
#ros-noetic-common-msgs \
ros-noetic-common-tutorials \
ros-noetic-cpp-common \
#ros-noetic-cv-bridge \
#ros-noetic-diagnostic-msgs \
ros-noetic-dynamic-reconfigure \
ros-noetic-eigen-stl-containers \
ros-noetic-gencpp \
ros-noetic-geneus \
ros-noetic-genlisp \
ros-noetic-genmsg \
ros-noetic-gennodejs \
ros-noetic-genpy \
#ros-noetic-geometry-msgs \
ros-noetic-image-transport \
ros-noetic-joint-state-publisher \
ros-noetic-message-filters \
ros-noetic-message-generation \
ros-noetic-message-runtime \
ros-noetic-mk \
ros-noetic-nav-msgs \
#ros-noetic-nodelet \
ros-noetic-nodelet-core \
ros-noetic-nodelet-topic-tools \
ros-noetic-nodelet-tutorial-math \
ros-noetic-pluginlib \
ros-noetic-pluginlib-tutorials \
ros-noetic-python-qt-binding \
ros-noetic-qt-dotgraph \
ros-noetic-qt-gui \
ros-noetic-qt-gui-cpp \
ros-noetic-qt-gui-py-common \
ros-noetic-qwt-dependency \
ros-noetic-ros \
ros-noetic-ros-base \
ros-noetic-ros-comm \
ros-noetic-ros-core \
#ros-noetic-ros-environment \
#ros-noetic-rosbag \
#ros-noetic-rosbag-migration-rule \
#ros-noetic-rosbag-storage \
ros-noetic-rosbash \
ros-noetic-rosboost-cfg \
#ros-noetic-rosbuild \
#ros-noetic-rosclean \
#ros-noetic-rosconsole \
ros-noetic-rosconsole-bridge \
ros-noetic-roscpp \
ros-noetic-roscpp-core \
ros-noetic-roscpp-serialization \
ros-noetic-roscpp-traits \
ros-noetic-roscreate \
ros-noetic-rosgraph \
#ros-noetic-rosgraph-msgs \
#ros-noetic-roslang \
#ros-noetic-roslaunch \
#ros-noetic-roslib \
ros-noetic-roslint \
ros-noetic-roslisp \
ros-noetic-roslz4 \
ros-noetic-rosmake \
#ros-noetic-rosmaster \
ros-noetic-rosmsg \
ros-noetic-rosnode \
#ros-noetic-rosout \
#ros-noetic-rospack \
#ros-noetic-rosparam \
#ros-noetic-rospy \
ros-noetic-rosservice \
#ros-noetic-rostest \
ros-noetic-rostime \
#ros-noetic-rostopic \
#ros-noetic-rosunit \
ros-noetic-roswtf \
ros-noetic-rqt-action \
ros-noetic-rqt-bag \
ros-noetic-rqt-bag-plugins \
ros-noetic-rqt-common-plugins \
ros-noetic-rqt-console \
ros-noetic-rqt-dep \
ros-noetic-rqt-graph \
ros-noetic-rqt-gui \
ros-noetic-rqt-gui-cpp \
ros-noetic-rqt-gui-py \
ros-noetic-rqt-image-view \
ros-noetic-rqt-launch \
ros-noetic-rqt-logger-level \
ros-noetic-rqt-msg \
ros-noetic-rqt-plot \
ros-noetic-rqt-publisher \
ros-noetic-rqt-py-common \
ros-noetic-rqt-py-console \
ros-noetic-rqt-reconfigure \
ros-noetic-rqt-service-caller \
ros-noetic-rqt-shell \
ros-noetic-rqt-srv \
ros-noetic-rqt-top \
ros-noetic-rqt-topic \
ros-noetic-rqt-web \
ros-noetic-sensor-msgs \
ros-noetic-shape-msgs \
#ros-noetic-smclib \
#ros-noetic-std-msgs \
#ros-noetic-std-srvs \
ros-noetic-stereo-msgs \
ros-noetic-tf \
ros-noetic-tf2 \
ros-noetic-tf2-msgs \
ros-noetic-tf2-py \
ros-noetic-tf2-ros \
#ros-noetic-topic-tools \
ros-noetic-trajectory-msgs \
ros-noetic-turtle-actionlib \
ros-noetic-turtlesim \
ros-noetic-visualization-msgs \
ros-noetic-webkit-dependency \
ros-noetic-xacro \
#ros-noetic-xmlrpcpp
